" Load Plug
source ~/.vim/config/plugins.vim

" Load configs
source ~/.vim/config/general/colors.vim
source ~/.vim/config/general/copypaste.vim
source ~/.vim/config/general/indentation.vim
source ~/.vim/config/general/maps.vim
source ~/.vim/config/general/screen.vim
source ~/.vim/config/general/tempfiles.vim

" Load plugins
source ~/.vim/config/plugins/ctrlp.vim
source ~/.vim/config/plugins/fugitive.vim
source ~/.vim/config/plugins/nerdtree.vim
source ~/.vim/config/plugins/tabular.vim
source ~/.vim/config/plugins/vim-buffergator.vim
source ~/.vim/config/plugins/vimux.vim
source ~/.vim/config/plugins/vimux-ruby-test.vim
source ~/.vim/config/plugins/alternate.vim
source ~/.vim/config/plugins/splitjoin.vim
source ~/.vim/config/plugins/syntastic.vim
